import Layout from "@/components/Layout";
import {
  Box,
  Container,
  Flex,
  GridItem,
  Heading,
  SimpleGrid,
  Text,
} from "@chakra-ui/react";
import Head from "next/head";
import { NextPageWithLayout } from "../_app";

const Filters = () => {
  return <Flex>Filters</Flex>;
};

const MetricBox = () => {
  return (
    <Flex px="18px" py="16px" rounded="8px" bg="white">
      Filters
    </Flex>
  );
};

const Page: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>httui - Pagina inicial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container mt="40px" px="40px">
        <Flex justify="space-between">
          <Box>
            <Heading color="black.700">Dashboard</Heading>
            <Text fontWeight="bold" color="black.400">
              principal / dashboard
            </Text>
          </Box>
          <Filters />
        </Flex>

        <Flex mt="40px" justify="space-between" gap="20px">
          <SimpleGrid w="full" columns={2} gap="20px">
            <GridItem w="full">
              <MetricBox />
            </GridItem>

            <GridItem w="full">
              <MetricBox />
            </GridItem>

            <GridItem w="full">
              <MetricBox />
            </GridItem>

            <GridItem w="full">
              <MetricBox />
            </GridItem>
          </SimpleGrid>

          <Box w="full">Graficos</Box>
        </Flex>
      </Container>
    </>
  );
};

Page.getLayout = function getLayout(page: React.ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Page;
